In [1]:
import torch
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
import torch.nn as nn

In [8]:
data = pd.read_csv("MNIST/train.csv").values

In [44]:
class CNN(nn.Module):
    def __init__(self, in_channel, out_channel):
        super(CNN, self).__init__()
        self.in_channel = in_channel
        self.out_channel = out_channel
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channel, 16, 5, bias=False),
            nn.LeakyReLU(0.1),
            nn.MaxPool2d(3, stride=2, padding=1)
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(16, 32, 3, bias=False),
            nn.LeakyReLU(0.1),
            nn.MaxPool2d(3, stride=2, padding=1)
        )
        self.out = nn.Sequential(
            nn.Linear(800, out_channel),
            nn.Sigmoid()
        )
    
    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = x.view(x.size(0), -1)
        x = self.out(x)
        return x

In [47]:
test = torch.ones((5,1,28,28))

In [41]:
class IDNGenerator:
    def __init__(self, X, y, p, epochs, model, optimizer):
        self.X = X
        self.y = y
        self.p = p
        self.epochs = epochs
        self.model = model
        self.optimizer = optimizer
        
    def train(self, X, y, )
    
    def generate(self):
        

SyntaxError: unexpected EOF while parsing (<ipython-input-41-02799ad92d9c>, line 9)

In [52]:
p1 = torch.ones((5,1,32,32))
p2 = torch.ones((5,1,32,32))
p3 = [p1,p2]

In [57]:
sum(p3) / len(p3)

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]]],


        [[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
    

In [58]:
class MNISTNoiseDataset(Dataset):
    def __init__(self, csv_file, transform=None):
        self.data = pd.read_csv(csv_file).values
        self.transform = transform
        
    def __len__(self):
        return self.data.shape[0]
        
    def __getitem__(self, index):
        X = self.data[index, 1:].reshape(28,28)
        y = self.data[index, 0]
        if self.transform:
            X = self.transform(X)
        return X, y

In [60]:
dataset = MNISTNoiseDataset(csv_file = "MNIST/train.csv", transform=transforms.ToTensor())

In [61]:
batch_size = 50
train_loader = DataLoader(dataset=dataset, batch_size=50, shuffle=False)

In [62]:
for x,y in train_loader:
    print(x.shape, y.shape)
    
    break

torch.Size([50, 1, 28, 28]) torch.Size([50])


In [244]:
x = torch.zeros((5,10)) + 2

In [245]:
y = torch.arange(5)*2+1

In [247]:
one_hot = torch.zeros((y.size(0), y.max() + 1))
one_hot[np.arange(y.size(0)), y] = True

In [250]:
x[one_hot.to(torch.bool)] = 0

In [251]:
x

tensor([[2., 0., 2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 0., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 0., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 0., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 0.]])

In [259]:
torch.amax(x, 1)

tensor([2., 2., 2., 2., 2.])

In [253]:
torch.argmax(x, 1)

tensor([0, 0, 0, 0, 0])